services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-app
    container_name: nextjs-app
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    command: npm run start